// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx0Mwt6TgnF4s3f-JIjZJ08nLNKqs37mw',
    appId: '1:945547363766:web:2b677a52f1a3a8d26aed17',
    messagingSenderId: '945547363766',
    projectId: 'trabalho-final-cee76',
    authDomain: 'trabalho-final-cee76.firebaseapp.com',
    storageBucket: 'trabalho-final-cee76.firebasestorage.app',
    measurementId: 'G-2SMTY8QH72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7reVOgw3yILV2WL47XHm--Bd_tSU4F7A',
    appId: '1:945547363766:android:c11070e333e824e16aed17',
    messagingSenderId: '945547363766',
    projectId: 'trabalho-final-cee76',
    storageBucket: 'trabalho-final-cee76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFJQ78yNkPFFRO7_MaRXTobyYTSImOlyo',
    appId: '1:945547363766:ios:ebb152d50b293b9b6aed17',
    messagingSenderId: '945547363766',
    projectId: 'trabalho-final-cee76',
    storageBucket: 'trabalho-final-cee76.firebasestorage.app',
    iosClientId:
        '945547363766-u4h67gbumbq8bbkp2bbqo3t3cr8vi4id.apps.googleusercontent.com',
    iosBundleId: 'com.example.trabalhoFinal',
  );
}
